"""Canonical Edge Type Definitions (Wave 3)."""
from __future__ import annotations

from typing import Any

#: Canonical Edge Type Registry: strictly ONE (src_type, tgt_type) per edge_type.
EDGE_TYPE_REGISTRY: dict[str, dict[str, Any]] = {
    # --- Taxonomy & Knowledge Spine (traversable=1) ---
    "career_track_contains_epoch": {
        "edge_type": "career_track_contains_epoch",
        "src_type": "career_track",
        "tgt_type": "career_epoch",
        "assertion_type": "STRUCTURAL_CONTAINMENT",
        "layer": "knowledge",
        "traversable": 1,
        "inverse_label": "epoch_in_career_track",
        "cardinality": "one_to_many",
    },
    "career_track_contains_pillar": {
        "edge_type": "career_track_contains_pillar",
        "src_type": "career_track",
        "tgt_type": "pillar",
        "assertion_type": "STRUCTURAL_CONTAINMENT",
        "layer": "knowledge",
        "traversable": 1,
        "inverse_label": "pillar_in_career_track",
        "cardinality": "one_to_many",
    },
    "career_track_contains_capability_domain": {
        "edge_type": "career_track_contains_capability_domain",
        "src_type": "career_track",
        "tgt_type": "capability_domain",
        "assertion_type": "STRUCTURAL_CONTAINMENT",
        "layer": "knowledge",
        "traversable": 1,
        "inverse_label": "domain_in_career_track",
        "cardinality": "one_to_many",
    },
    "career_track_precedes_career_track": {
        "edge_type": "career_track_precedes_career_track",
        "src_type": "career_track",
        "tgt_type": "career_track",
        "assertion_type": "TEMPORAL_SEQUENCE",
        "layer": "temporal",
        "traversable": 1,
        "inverse_label": "career_track_succeeds_career_track",
        "cardinality": "one_to_one",
    },
    "epoch_contains_pillar": {
        "edge_type": "epoch_contains_pillar",
        "src_type": "career_epoch",
        "tgt_type": "pillar",
        "assertion_type": "STRUCTURAL_CONTAINMENT",
        "layer": "knowledge",
        "traversable": 1,
        "inverse_label": "pillar_in_epoch",
        "cardinality": "many_to_many",
    },
    "epoch_contains_skill": {
        "edge_type": "epoch_contains_skill",
        "src_type": "career_epoch",
        "tgt_type": "skill",
        "assertion_type": "STRUCTURAL_CONTAINMENT",
        "layer": "knowledge",
        "traversable": 1,
        "inverse_label": "skill_in_epoch",
        "cardinality": "one_to_many",
    },
    "pillar_contains_capability_domain": {
        "edge_type": "pillar_contains_capability_domain",
        "src_type": "pillar",
        "tgt_type": "capability_domain",
        "assertion_type": "STRUCTURAL_CONTAINMENT",
        "layer": "knowledge",
        "traversable": 1,
        "inverse_label": "domain_in_pillar",
        "cardinality": "one_to_many",
    },
    "pillar_contains_skill": {
        "edge_type": "pillar_contains_skill",
        "src_type": "pillar",
        "tgt_type": "skill",
        "assertion_type": "STRUCTURAL_CONTAINMENT",
        "layer": "knowledge",
        "traversable": 1,
        "inverse_label": "skill_in_pillar",
        "cardinality": "one_to_many",
    },
    "capability_domain_contains_skill": {
        "edge_type": "capability_domain_contains_skill",
        "src_type": "capability_domain",
        "tgt_type": "skill",
        "assertion_type": "STRUCTURAL_CONTAINMENT",
        "layer": "knowledge",
        "traversable": 1,
        "inverse_label": "skill_in_domain",
        "cardinality": "one_to_many",
    },
    "pillar_phase_bridge": {
        "edge_type": "pillar_phase_bridge",
        "src_type": "pillar",
        "tgt_type": "pillar",
        "assertion_type": "ASSOCIATIVE_BRIDGE",
        "layer": "knowledge",
        "traversable": 1,
        "inverse_label": "pillar_phase_bridge_reverse",
        "cardinality": "many_to_many",
    },
    "skill_reinforces_skill": {
        "edge_type": "skill_reinforces_skill",
        "src_type": "skill",
        "tgt_type": "skill",
        "assertion_type": "ASSOCIATIVE_BRIDGE",
        "layer": "knowledge",
        "traversable": 1,
        "inverse_label": "skill_reinforced_by_skill",
        "cardinality": "many_to_many",
    },
    "identity_supported_by_pillar": {
        "edge_type": "identity_supported_by_pillar",
        "src_type": "role_family",
        "tgt_type": "pillar",
        "assertion_type": "TAXONOMIC_ATTRIBUTION",
        "layer": "knowledge",
        "traversable": 1,
        "inverse_label": "pillar_supports_identity",
        "cardinality": "many_to_many",
    },
    "identity_supported_by_epoch": {
        "edge_type": "identity_supported_by_epoch",
        "src_type": "role_family",
        "tgt_type": "career_epoch",
        "assertion_type": "TAXONOMIC_ATTRIBUTION",
        "layer": "knowledge",
        "traversable": 1,
        "inverse_label": "epoch_supports_identity",
        "cardinality": "many_to_many",
    },
    "metric_bucket_contains_metric": {
        "edge_type": "metric_bucket_contains_metric",
        "src_type": "metric_bucket",
        "tgt_type": "metric",
        "assertion_type": "STRUCTURAL_CONTAINMENT",
        "layer": "knowledge",
        "traversable": 1,
        "inverse_label": "metric_in_bucket",
        "cardinality": "one_to_many",
    },
    "skill_has_metric_bucket": {
        "edge_type": "skill_has_metric_bucket",
        "src_type": "skill",
        "tgt_type": "metric_bucket",
        "assertion_type": "STRUCTURAL_CONTAINMENT",
        "layer": "knowledge",
        "traversable": 1,
        "inverse_label": "metric_bucket_for_skill",
        "cardinality": "many_to_one",
    },
    "skill_can_surface_metric": {
        "edge_type": "skill_can_surface_metric",
        "src_type": "skill",
        "tgt_type": "metric",
        "assertion_type": "METRIC_BINDING",
        "layer": "knowledge",
        "traversable": 1,
        "inverse_label": "metric_surfaced_by_skill",
        "cardinality": "many_to_many",
    },

    # --- Evidence & Hierarchy Spine (traversable=1) ---
    "employment_hosts_fact": {
        "edge_type": "employment_hosts_fact",
        "src_type": "employment",
        "tgt_type": "fact",
        "assertion_type": "STRUCTURAL_CONTAINMENT",
        "layer": "evidence",
        "traversable": 1,
        "inverse_label": "fact_hosted_by_employment",
        "cardinality": "one_to_many",
    },
    "employment_in_career_track": {
        "edge_type": "employment_in_career_track",
        "src_type": "employment",
        "tgt_type": "career_track",
        "assertion_type": "TAXONOMIC_ATTRIBUTION",
        "layer": "evidence",
        "traversable": 1,
        "inverse_label": "career_track_contains_employment",
        "cardinality": "many_to_one",
    },
    "employment_in_epoch": {
        "edge_type": "employment_in_epoch",
        "src_type": "employment",
        "tgt_type": "career_epoch",
        "assertion_type": "TEMPORAL_SEQUENCE",
        "layer": "temporal",
        "traversable": 1,
        "inverse_label": "epoch_contains_employment",
        "cardinality": "many_to_one",
    },
    "employment_produces_skill": {
        "edge_type": "employment_produces_skill",
        "src_type": "employment",
        "tgt_type": "skill",
        "assertion_type": "EVIDENTIAL_SUPPORT",
        "layer": "evidence",
        "traversable": 1,
        "inverse_label": "skill_produced_by_employment",
        "cardinality": "many_to_many",
    },
    "skill_supported_by_fact": {
        "edge_type": "skill_supported_by_fact",
        "src_type": "skill",
        "tgt_type": "fact",
        "assertion_type": "EVIDENTIAL_SUPPORT",
        "layer": "evidence",
        "traversable": 1,
        "inverse_label": "fact_supports_skill",
        "cardinality": "many_to_many",
    },
    "skill_supported_by_locked_bullet": {
        "edge_type": "skill_supported_by_locked_bullet",
        "src_type": "skill",
        "tgt_type": "locked_bullet",
        "assertion_type": "EVIDENTIAL_SUPPORT",
        "layer": "evidence",
        "traversable": 1,
        "inverse_label": "locked_bullet_supports_skill",
        "cardinality": "many_to_many",
    },
    "skill_supported_by_employment": {
        "edge_type": "skill_supported_by_employment",
        "src_type": "skill",
        "tgt_type": "employment",
        "assertion_type": "EVIDENTIAL_SUPPORT",
        "layer": "evidence",
        "traversable": 1,
        "inverse_label": "employment_supports_skill",
        "cardinality": "many_to_many",
    },
    "skill_supported_by_certification": {
        "edge_type": "skill_supported_by_certification",
        "src_type": "skill",
        "tgt_type": "certification",
        "assertion_type": "EVIDENTIAL_SUPPORT",
        "layer": "evidence",
        "traversable": 1,
        "inverse_label": "certification_supports_skill",
        "cardinality": "many_to_many",
    },
    "skill_supported_by_repo_evidence": {
        "edge_type": "skill_supported_by_repo_evidence",
        "src_type": "skill",
        "tgt_type": "repo_evidence",
        "assertion_type": "EVIDENTIAL_SUPPORT",
        "layer": "evidence",
        "traversable": 1,
        "inverse_label": "repo_evidence_supports_skill",
        "cardinality": "many_to_many",
    },
    "skill_supported_by_source_concept": {
        "edge_type": "skill_supported_by_source_concept",
        "src_type": "skill",
        "tgt_type": "concept",
        "assertion_type": "EVIDENTIAL_SUPPORT",
        "layer": "evidence",
        "traversable": 1,
        "inverse_label": "source_concept_supports_skill",
        "cardinality": "many_to_many",
    },
    "skill_surfaces_metric_outcome": {
        "edge_type": "skill_surfaces_metric_outcome",
        "src_type": "skill",
        "tgt_type": "metric_outcome",
        "assertion_type": "METRIC_BINDING",
        "layer": "evidence",
        "traversable": 1,
        "inverse_label": "metric_outcome_surfaced_by_skill",
        "cardinality": "many_to_many",
    },
    "fact_has_metric_outcome": {
        "edge_type": "fact_has_metric_outcome",
        "src_type": "fact",
        "tgt_type": "metric_outcome",
        "assertion_type": "METRIC_BINDING",
        "layer": "evidence",
        "traversable": 1,
        "inverse_label": "metric_outcome_from_fact",
        "cardinality": "one_to_many",
    },
    "locked_bullet_has_metric_outcome": {
        "edge_type": "locked_bullet_has_metric_outcome",
        "src_type": "locked_bullet",
        "tgt_type": "metric_outcome",
        "assertion_type": "METRIC_BINDING",
        "layer": "evidence",
        "traversable": 1,
        "inverse_label": "metric_outcome_from_locked_bullet",
        "cardinality": "one_to_many",
    },
    "metric_outcome_bound_to_employer": {
        "edge_type": "metric_outcome_bound_to_employer",
        "src_type": "metric_outcome",
        "tgt_type": "employment",
        "assertion_type": "METRIC_BINDING",
        "layer": "evidence",
        "traversable": 1,
        "inverse_label": "employer_hosts_metric_outcome",
        "cardinality": "many_to_one",
    },
    "metric_outcome_anchors_bundle": {
        "edge_type": "metric_outcome_anchors_bundle",
        "src_type": "metric_outcome",
        "tgt_type": "engagement",
        "assertion_type": "METRIC_BINDING",
        "layer": "evidence",
        "traversable": 1,
        "inverse_label": "bundle_anchored_by_metric_outcome",
        "cardinality": "many_to_many",
    },

    # --- First-Class Engagement Edges (traversable=1) ---
    "engagement_at_employment": {
        "edge_type": "engagement_at_employment",
        "src_type": "engagement",
        "tgt_type": "employment",
        "assertion_type": "STRUCTURAL_CONTAINMENT",
        "layer": "evidence",
        "traversable": 1,
        "inverse_label": "employment_hosts_engagement",
        "cardinality": "many_to_one",
    },
    "engagement_exercises_skill": {
        "edge_type": "engagement_exercises_skill",
        "src_type": "engagement",
        "tgt_type": "skill",
        "assertion_type": "EVIDENTIAL_SUPPORT",
        "layer": "evidence",
        "traversable": 1,
        "inverse_label": "skill_exercised_in_engagement",
        "cardinality": "many_to_many",
    },
    "engagement_evidenced_by_fact": {
        "edge_type": "engagement_evidenced_by_fact",
        "src_type": "engagement",
        "tgt_type": "fact",
        "assertion_type": "EVIDENTIAL_SUPPORT",
        "layer": "evidence",
        "traversable": 1,
        "inverse_label": "fact_evidences_engagement",
        "cardinality": "many_to_many",
    },

    # --- Policy & Projection Layer (traversable=0) ---
    "skill_allowed_in_section": {
        "edge_type": "skill_allowed_in_section",
        "src_type": "skill",
        "tgt_type": "section",
        "assertion_type": "POLICY_ELIGIBILITY",
        "layer": "policy",
        "traversable": 0,
        "inverse_label": "section_allows_skill",
        "cardinality": "many_to_many",
    },
    "section_can_select_skill": {
        "edge_type": "section_can_select_skill",
        "src_type": "section",
        "tgt_type": "skill",
        "assertion_type": "POLICY_ELIGIBILITY",
        "layer": "policy",
        "traversable": 0,
        "inverse_label": "skill_selectable_by_section",
        "cardinality": "many_to_many",
    },
    "pillar_section_eligibility": {
        "edge_type": "pillar_section_eligibility",
        "src_type": "pillar",
        "tgt_type": "section",
        "assertion_type": "POLICY_ELIGIBILITY",
        "layer": "policy",
        "traversable": 0,
        "inverse_label": "section_eligibility_for_pillar",
        "cardinality": "many_to_many",
    },
    "metric_outcome_section_eligible": {
        "edge_type": "metric_outcome_section_eligible",
        "src_type": "metric_outcome",
        "tgt_type": "section",
        "assertion_type": "POLICY_ELIGIBILITY",
        "layer": "policy",
        "traversable": 0,
        "inverse_label": "section_admits_metric_outcome",
        "cardinality": "many_to_many",
    },
    "skill_external_claim_eligible": {
        "edge_type": "skill_external_claim_eligible",
        "src_type": "skill",
        "tgt_type": "policy",
        "assertion_type": "POLICY_ELIGIBILITY",
        "layer": "policy",
        "traversable": 0,
        "inverse_label": "policy_admits_skill_external_claim",
        "cardinality": "many_to_one",
    },
    "skill_projection_only_internal": {
        "edge_type": "skill_projection_only_internal",
        "src_type": "skill",
        "tgt_type": "policy",
        "assertion_type": "POLICY_RESTRICTION",
        "layer": "policy",
        "traversable": 0,
        "inverse_label": "policy_restricts_skill_internal",
        "cardinality": "many_to_one",
    },
    "skill_requires_human_confirmation": {
        "edge_type": "skill_requires_human_confirmation",
        "src_type": "skill",
        "tgt_type": "policy",
        "assertion_type": "POLICY_RESTRICTION",
        "layer": "policy",
        "traversable": 0,
        "inverse_label": "policy_requires_human_confirmation_for_skill",
        "cardinality": "many_to_one",
    },
    "projection_excludes_blocked_skill": {
        "edge_type": "projection_excludes_blocked_skill",
        "src_type": "skill",
        "tgt_type": "policy",
        "assertion_type": "POLICY_RESTRICTION",
        "layer": "policy",
        "traversable": 0,
        "inverse_label": "policy_excludes_blocked_skill",
        "cardinality": "many_to_one",
    },
    "srfs_rule_requires_fact_id_only": {
        "edge_type": "srfs_rule_requires_fact_id_only",
        "src_type": "policy_rule",
        "tgt_type": "policy",
        "assertion_type": "POLICY_RESTRICTION",
        "layer": "policy",
        "traversable": 0,
        "inverse_label": "policy_governed_by_rule",
        "cardinality": "many_to_one",
    },
    "srfs_policy_requires_fact_id_only": {
        "edge_type": "srfs_policy_requires_fact_id_only",
        "src_type": "policy",
        "tgt_type": "policy",
        "assertion_type": "POLICY_RESTRICTION",
        "layer": "policy",
        "traversable": 0,
        "inverse_label": "policy_relies_on_policy",
        "cardinality": "many_to_one",
    },
    "section_blocks_pending_source_skill": {
        "edge_type": "section_blocks_pending_source_skill",
        "src_type": "section",
        "tgt_type": "policy_rule",
        "assertion_type": "POLICY_RESTRICTION",
        "layer": "policy",
        "traversable": 0,
        "inverse_label": "rule_blocks_pending_source_skill",
        "cardinality": "many_to_one",
    },
    "section_blocks_skill_without_fact": {
        "edge_type": "section_blocks_skill_without_fact",
        "src_type": "section",
        "tgt_type": "policy_rule",
        "assertion_type": "POLICY_RESTRICTION",
        "layer": "policy",
        "traversable": 0,
        "inverse_label": "rule_blocks_skill_without_fact",
        "cardinality": "many_to_one",
    },
    "jd_briefing_targeting_only": {
        "edge_type": "jd_briefing_targeting_only",
        "src_type": "graph_ref",
        "tgt_type": "policy_rule",
        "assertion_type": "POLICY_RESTRICTION",
        "layer": "policy",
        "traversable": 0,
        "inverse_label": "rule_targets_briefing_only",
        "cardinality": "one_to_one",
    },
}

__all__ = ["EDGE_TYPE_REGISTRY"]
