"""Default section evidence budgets for all 17 resume lanes (Wave 3)."""
from __future__ import annotations

from typing import Any

DEFAULT_SECTION_BUDGETS: tuple[dict[str, Any], ...] = (
    {
        "section_id": "section_executive_summary",
        "role_family_key": "*",
        "max_metric_reuse": 1,
        "max_fact_family_reuse": 2,
        "required_node_types": ["skill", "fact", "metric_outcome"],
        "preferred_edge_types": [
            "identity_supported_by_pillar",
            "skill_supported_by_fact",
            "fact_has_metric_outcome",
        ],
        "forbidden_metric_ids": [],
        "preferred_metric_families": [
            "revenue_growth",
            "risk_governance",
            "platform_scale",
            "adoption_enablement",
        ],
    },
    {
        "section_id": "section_competencies",
        "role_family_key": "*",
        "max_metric_reuse": 0,
        "max_fact_family_reuse": 1,
        "required_node_types": ["skill", "pillar"],
        "preferred_edge_types": ["capability_domain_contains_skill", "pillar_contains_skill"],
        "forbidden_metric_ids": [],
        "preferred_metric_families": ["platform_scale", "model_quality", "delivery_velocity"],
    },
    {
        "section_id": "section_experience",
        "role_family_key": "*",
        "max_metric_reuse": 1,
        "max_fact_family_reuse": 2,
        "required_node_types": ["skill", "fact", "metric_outcome"],
        "preferred_edge_types": [
            "skill_supported_by_fact",
            "employment_hosts_fact",
            "fact_has_metric_outcome",
        ],
        "forbidden_metric_ids": [],
        "preferred_metric_families": ["cost_efficiency", "revenue_growth", "delivery_velocity"],
    },
    {
        "section_id": "section_leadership",
        "role_family_key": "*",
        "max_metric_reuse": 1,
        "max_fact_family_reuse": 2,
        "required_node_types": ["skill", "fact"],
        "preferred_edge_types": [
            "identity_supported_by_pillar",
            "employment_hosts_fact",
            "skill_supported_by_fact",
        ],
        "forbidden_metric_ids": [],
        "preferred_metric_families": ["revenue_growth", "adoption_enablement", "partner_gtm"],
    },
    {
        "section_id": "section_technical_architecture",
        "role_family_key": "*",
        "max_metric_reuse": 1,
        "max_fact_family_reuse": 2,
        "required_node_types": ["skill", "fact", "metric_outcome"],
        "preferred_edge_types": [
            "capability_domain_contains_skill",
            "skill_supported_by_fact",
            "fact_has_metric_outcome",
        ],
        "forbidden_metric_ids": [],
        "preferred_metric_families": ["platform_scale", "risk_governance", "model_quality"],
    },
    {
        "section_id": "section_early_career",
        "role_family_key": "*",
        "max_metric_reuse": 0,
        "max_fact_family_reuse": 1,
        "required_node_types": ["skill", "fact"],
        "preferred_edge_types": ["skill_supported_by_fact", "employment_hosts_fact"],
        "forbidden_metric_ids": [],
        "preferred_metric_families": ["cost_efficiency"],
    },
    {
        "section_id": "section_headline",
        "role_family_key": "*",
        "max_metric_reuse": 0,
        "max_fact_family_reuse": 0,
        "required_node_types": ["skill"],
        "preferred_edge_types": ["capability_domain_contains_skill"],
        "forbidden_metric_ids": [],
        "preferred_metric_families": [],
    },
    {
        "section_id": "section_slalom_bullets",
        "role_family_key": "*",
        "max_metric_reuse": 1,
        "max_fact_family_reuse": 2,
        "required_node_types": ["skill", "fact", "metric_outcome"],
        "preferred_edge_types": ["skill_supported_by_fact", "employment_hosts_fact", "fact_has_metric_outcome"],
        "forbidden_metric_ids": [],
        "preferred_metric_families": ["revenue_growth", "platform_scale", "delivery_velocity"],
    },
    {
        "section_id": "section_slalom_narrative",
        "role_family_key": "*",
        "max_metric_reuse": 1,
        "max_fact_family_reuse": 2,
        "required_node_types": ["skill", "fact", "metric_outcome"],
        "preferred_edge_types": ["skill_supported_by_fact", "employment_hosts_fact", "fact_has_metric_outcome"],
        "forbidden_metric_ids": [],
        "preferred_metric_families": ["revenue_growth", "platform_scale", "delivery_velocity"],
    },
    {
        "section_id": "section_unify_bullets",
        "role_family_key": "*",
        "max_metric_reuse": 1,
        "max_fact_family_reuse": 2,
        "required_node_types": ["skill", "fact", "metric_outcome"],
        "preferred_edge_types": ["skill_supported_by_fact", "employment_hosts_fact", "fact_has_metric_outcome"],
        "forbidden_metric_ids": [],
        "preferred_metric_families": ["revenue_growth", "platform_scale", "delivery_velocity"],
    },
    {
        "section_id": "section_unify_narrative",
        "role_family_key": "*",
        "max_metric_reuse": 1,
        "max_fact_family_reuse": 2,
        "required_node_types": ["skill", "fact", "metric_outcome"],
        "preferred_edge_types": ["skill_supported_by_fact", "employment_hosts_fact", "fact_has_metric_outcome"],
        "forbidden_metric_ids": [],
        "preferred_metric_families": ["revenue_growth", "platform_scale", "delivery_velocity"],
    },
    {
        "section_id": "section_ibm_bullets",
        "role_family_key": "*",
        "max_metric_reuse": 1,
        "max_fact_family_reuse": 2,
        "required_node_types": ["skill", "fact", "metric_outcome"],
        "preferred_edge_types": ["skill_supported_by_fact", "employment_hosts_fact", "fact_has_metric_outcome"],
        "forbidden_metric_ids": [],
        "preferred_metric_families": ["revenue_growth", "platform_scale", "delivery_velocity"],
    },
    {
        "section_id": "section_ibm_narrative",
        "role_family_key": "*",
        "max_metric_reuse": 1,
        "max_fact_family_reuse": 2,
        "required_node_types": ["skill", "fact", "metric_outcome"],
        "preferred_edge_types": ["skill_supported_by_fact", "employment_hosts_fact", "fact_has_metric_outcome"],
        "forbidden_metric_ids": [],
        "preferred_metric_families": ["revenue_growth", "platform_scale", "delivery_velocity"],
    },
    {
        "section_id": "section_insurtech_bullets",
        "role_family_key": "*",
        "max_metric_reuse": 1,
        "max_fact_family_reuse": 2,
        "required_node_types": ["skill", "fact", "metric_outcome"],
        "preferred_edge_types": ["skill_supported_by_fact", "employment_hosts_fact", "fact_has_metric_outcome"],
        "forbidden_metric_ids": [],
        "preferred_metric_families": ["cost_efficiency", "platform_scale", "delivery_velocity"],
    },
    {
        "section_id": "section_insurtech_narrative",
        "role_family_key": "*",
        "max_metric_reuse": 1,
        "max_fact_family_reuse": 2,
        "required_node_types": ["skill", "fact", "metric_outcome"],
        "preferred_edge_types": ["skill_supported_by_fact", "employment_hosts_fact", "fact_has_metric_outcome"],
        "forbidden_metric_ids": [],
        "preferred_metric_families": ["cost_efficiency", "platform_scale", "delivery_velocity"],
    },
    {
        "section_id": "section_ey_bullets",
        "role_family_key": "*",
        "max_metric_reuse": 1,
        "max_fact_family_reuse": 2,
        "required_node_types": ["skill", "fact", "metric_outcome"],
        "preferred_edge_types": ["skill_supported_by_fact", "employment_hosts_fact", "fact_has_metric_outcome"],
        "forbidden_metric_ids": [],
        "preferred_metric_families": ["risk_governance", "cost_efficiency", "revenue_growth"],
    },
    {
        "section_id": "section_ey_narrative",
        "role_family_key": "*",
        "max_metric_reuse": 1,
        "max_fact_family_reuse": 2,
        "required_node_types": ["skill", "fact", "metric_outcome"],
        "preferred_edge_types": ["skill_supported_by_fact", "employment_hosts_fact", "fact_has_metric_outcome"],
        "forbidden_metric_ids": [],
        "preferred_metric_families": ["risk_governance", "cost_efficiency", "revenue_growth"],
    },
)

__all__ = ["DEFAULT_SECTION_BUDGETS"]
